### PR TITLE
Printing and saving PFLOW output

### PR DESCRIPTION
**Pull request by abhyshr**
Output for PFLOW

- Save output in multiple formats (same as OPFLOW) - MATPOWER, JSON, and CSV
- Printing output to screen
- Support reading gic file and ingest data from it for visualization

### CODE REVIEW

**Comment by abhyshr** [comment]
@wperkins : Please review if you have time.

**Comment by abhyshr** [comment]
@jaelynlitz @cameronrutherford   any idea why the pre-commit is failing?

**Comment by cameronrutherford** [comment]
> @jaelynlitz @cameronrutherford any idea why the pre-commit is failing?

pre-commit failed, and then successfully made a commit that fixed your changes. It skipped CI with that commit to not duplicate anything, and all other checks in your pipeline pass.

I would consider this pipelines working as intended, and you can always install pre-commit locally to ensure the checks are run proactively.

**Comment by cameronrutherford** [comment]
> > @jaelynlitz @cameronrutherford any idea why the pre-commit is failing?
> 
> pre-commit failed, and then successfully made a commit that fixed your changes. It skipped CI with that commit to not duplicate anything, and all other checks in your pipeline pass.
> 
> I would consider this pipelines working as intended, and you can always install pre-commit locally to ensure the checks are run proactively.

Our current `pre-commit` docs are in #85 [here](https://github.com/pnnl/ExaGO/blob/spack-ubuntu-cache-dev/.github/workflows/README.md#pre_commityaml). Let me know if you want that improved/clarified. I can also add a small user guide for pre-commit to main README...

**Review by cameronrutherford — APPROVED** [review]
Would love to see some documentation added somewhere to document the new feature

**Comment by abhyshr** [comment]
Yes, documentation and python api coming up through another PR.

**Pull request merged**
