### PR TITLE
SCOPFLOW HiOp Patch

### LINKED ISSUE #3: SCOPFLOW Functionality Tests failing with `hiop@1.0.0`
Issue type: Bug  
Relates to: 
- SCOPFLOW  
- CMake build system  
- Spack configuration  

Summary:

Incline CI fails on the following tests:
Failed Pipeline:
https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/jobs/125455
Raw Job output:
https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/jobs/125455/raw
The objective value and expected values are not within tolerance. Meaning we could increase tolerance or change the expected value for tests that run on Incline.
Things to further do:
Confirm Hiop version
Run Crusher test and compare objective values across platforms.
FUNCTIONALITY_TEST_SCOPFLOW_HIOP_PBHIOP_TESTSUITE is failing for Newell at the moment as well - https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/jobs/126069

Types of failures:
- [X] divide by zero (various tests and platforms, incline, deception, newell) (FUNCTIONALITY_TEST_SCOPFLOW_HIOP_PBHIOP_TESTSUITE, FUNCTIONALITY_TEST_SCOPFLOW_HIOP_SERIAL_TESTSUITE, FUNCTIONALITY_TEST_SCOPFLOW_HIOP_RAJA_TESTSUITE)
- [X] num iters (FUNCTIONALITY_TEST_SCOPFLOW_HIOP_MPI_TESTSUITE, incline)
- [X] obj value out of tolerance (FUNCTIONALITY_TEST_SCOPFLOW_EMPAR_CONT_TESTSUITE, incline) 
- [ ] timeout (FUNCTIONALITY_TEST_SOPFLOW_SCENARIO_RAJA_GPU_TOML, incline)

### PR DESCRIPTION
**Pull request by jaelynlitz**
Initial Purpose: Fix divide by zero errors happening in SCOPFLOW - a hiop patch issue657-fix was added to resolve these issues. Just rebuilding with updated hiop and re-enabling those tests.
-> these errors were fixed in hiop@1.0.0

Current Purpose: build with hiop@develop (v1.0.1+) and resolve issues due to interface changes and compiler warnings.

Closes #3

### CODE REVIEW

**Comment by cameronrutherford** [comment]
Moving to 1.6.1 since this will come with resolving #28 and other issues

**Comment by cameronrutherford** [comment]
Can you kick off a rebuild as well so that we can use updated `hiop@develop`?

**Comment by nychiang** [comment]
@jaelynlitz  Do those tests work now?

**Comment by cameronrutherford** [comment]
There are a mix of HiOp and ExaGO build errors

**Comment by jaelynlitz** [comment]
> @jaelynlitz Do those tests work now?

@nychiang It looks like on Deception and Newell, hiop built successfully, but there are some type errors in our SCOPFLOW hiop interface https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135161#L325

**Comment by jaelynlitz** [comment]
@nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors

**Comment by jaelynlitz** [comment]
@nychiang Ascent's hiop build failed with less errors, some syntax warnings and an include file it couldn't find https://code.ornl.gov/ecpcitest/exasgd/exago/-/jobs/2147169#L180

**Comment by cameronrutherford** [comment]
> @nychiang Ascent's hiop build failed with less errors, some syntax warnings and an include file it couldn't find https://code.ornl.gov/ecpcitest/exasgd/exago/-/jobs/2147169#L180

For some reason it seems like submodules aren't being cloned with develop (eigen header is missing, which is a submodule). You might have to update the spack package for HiOp so that develop clones submodules.

**Comment by cameronrutherford** [comment]
> @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors

This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here

**Comment by cameronrutherford** [comment]
> > @jaelynlitz Do those tests work now?
> 
> @nychiang It looks like on Deception and Newell, hiop built successfully, but there are some type errors in our SCOPFLOW hiop interface https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135161#L325

I think these are resolved by #30

**Comment by nychiang** [comment]
> > @jaelynlitz Do those tests work now?
> 
> @nychiang It looks like on Deception and Newell, hiop built successfully, but there are some type errors in our SCOPFLOW hiop interface https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135161#L325

Yes, as @cameronrutherford mentioned, this has been fixed in PR#30

**Comment by nychiang** [comment]
> > @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors
> 
> This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here
We'd like to move "-Wall -Werror" flags to DEBUG mode, similar to ExaGO

**Comment by cameronrutherford** [comment]
> > > @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors
> > 
> > 
> > This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here
> > We'd like to move "-Wall -Werror" flags to DEBUG mode, similar to ExaGO

@nychiang if you can make an issue in HiOp to track this that would be great so we can patch that in.

Perhaps there is a way to avoid these compiler issues at the spack level in the meantime...

**Comment by jaelynlitz** [comment]
> > > @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors
> > 
> > 
> > This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here
> > We'd like to move "-Wall -Werror" flags to DEBUG mode, similar to ExaGO

So only use those flags when building in Debug mode, ignore in Release mode?

I also disagree with some of the "unused" vars the compiler is catching - it says the MPI `ierr` flags are never used even though the next statement is an assert to check `ierr`?


https://github.com/LLNL/hiop/blob/develop/src/Utils/hiopLogger.hpp#L96C5-L96C5 
https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135604#L468

**Comment by nychiang** [comment]
> > > > @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors
> > > 
> > > 
> > > This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here
> > > We'd like to move "-Wall -Werror" flags to DEBUG mode, similar to ExaGO
> 
> So only use those flags when building in Debug mode, ignore in Release mode?
> 
> I also disagree with some of the "unused" vars the compiler is catching - it says the MPI `ierr` flags are never used even though the next statement is an assert to check `ierr`?
> 
> https://github.com/LLNL/hiop/blob/develop/src/Utils/hiopLogger.hpp#L96C5-L96C5 https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135604#L468

That happens when we define `NDEBUG`, which may be added by some compilers in the release mode. When `NDEBUG` is given, all assertion will be ignored (https://en.cppreference.com/w/c/error/assert). As a result, `ierr` becomes unused.

The best approach to handle this is to build our own error control, or use C++17 and add attribute `maybe_unused` ( https://en.cppreference.com/w/cpp/language/attributes/maybe_unused)

@jaelynlitz

**Comment by cameronrutherford** [comment]
> > > > > @nychiang Incline's build of hiop failed https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135160#L212 seems to be mostly unused variable warnings/errors
> 
> > > > 
> 
> > > > 
> 
> > > > This probably requires a HiOp patch then to work through those unused variables since HiOp is the one failing here
> 
> > > > We'd like to move "-Wall -Werror" flags to DEBUG mode, similar to ExaGO
> 
> > 
> 
> > So only use those flags when building in Debug mode, ignore in Release mode?
> 
> > 
> 
> > I also disagree with some of the "unused" vars the compiler is catching - it says the MPI `ierr` flags are never used even though the next statement is an assert to check `ierr`?
> 
> > 
> 
> > https://github.com/LLNL/hiop/blob/develop/src/Utils/hiopLogger.hpp#L96C5-L96C5 https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/135604#L468
> 
> 
> 
> That happens when we define `NDEBUG`, which may be added by some compilers in the release mode. When `NDEBUG` is given, all assertion will be ignored (https://en.cppreference.com/w/c/error/assert). As a result, `ierr` becomes unused.
> 
> 
> 
> The best approach to handle this is to build our own error control, or use C++17 and add attribute `maybe_unused` ( https://en.cppreference.com/w/cpp/language/attributes/maybe_unused)
> 
> 
> 
> @jaelynlitz 

Maybe unused works, and iirc there are gnu directives that are C++14 compatible that also work around the warnings.

**Comment by nychiang** [comment]
@cameronrutherford do you mean adding "(void) ierr;". This helps, but it is ugly in my opinion. :-)

**Comment by cameronrutherford** [comment]
> @cameronrutherford do you mean adding "(void) ierr;". This helps, but it is ugly in my opinion. :-)

That's one approach. There's a pre-processor directive I'm thinking of...

@pelesh probably has a better idea here :)

**Comment by abhyshr** [comment]
Is this something because of PETSc? If so, I would recommend to use PETSc 3.20 and see if that resolves the issue. If not, let's send an email to PETSc mailing list. Satish or someone else from the PETSc team may be able to figure out what's happening here.

**Comment by cameronrutherford** [comment]
> Is this something because of PETSc? If so, I would recommend to use PETSc 3.20 and see if that resolves the issue. If not, let's send an email to PETSc mailing list. Satish or someone else from the PETSc team may be able to figure out what's happening here.

Alas this is isolated to HiOp and ExaGO :)

**Comment by jaelynlitz** [comment]
closing as this was wrapped into #84

**Pull request closed without merging**
